#!/bin/sh

set -eux

wp core download
wp config create \
    --dbname="$WP_DB" \
    --dbhost="$DB:$DB_PORT" \
    --dbuser="$WP_DB_USER" \
    --prompt=dbpass<<EOF
$WP_DB_PW
EOF
wp db create
wp core install \
    --url="$DOMAIN" \
    --title="Tischmid's site" \
    --admin_user="$WP_ADMIN_USER" \
    --admin_email="$WP_ADMIN_EMAIL" \
    --skip-email \
    --prompt=admin_password<<EOF
$WP_ADMIN_PW
EOF

unset WP_PW WP_ADMIN_PW

exec "$@"
